import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import Header from "./_components/header";
import "./globals.css";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "Next Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Provider>
          <Header />
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
